language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
install:
  - npm install

# Allow Travis tests to run in containers.
sudo: false

after_script:
  - "cat ./coverage/lcov.info | coveralls"
