language: node_js
node_js:
  - "8"
  - "7"
install:
  - npm install

# Allow Travis tests to run in containers.
sudo: false

after_script:
  - "cat ./coverage/lcov.info | coveralls"
  - "bithound check git@github.com:ouq77/express-user-agent-blocker.git"
