language: node_js
node_js:
  - "8"
  - "7"
  - "6"
install:
  - npm install

script:
  - npm test
  - npm run test:coverage:lcov

# Allow Travis tests to run in containers.
sudo: false

after_script: "cat ./coverage/lcov.info | coveralls"
