branches:
  only:
    - master

language: node_js
node_js:
  - "16"
  - "14"
install:
  - npm install

# Allow Travis tests to run in containers.
sudo: false

after_script:
  - "cat ./coverage/lcov.info | coveralls"
