language: node_js
node_js:
  - "18"
  - "16"
  - "14"
  - "12"
  - "10"
install:
  - npm install

# Allow Travis tests to run in containers.
sudo: false

after_script:
  - "cat ./coverage/lcov.info | coveralls"
